apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cruise-control.fullname" . }}-config
  labels:
    {{- include "cruise-control.labels" . | nindent 4 }}
data:
  cruisecontrol.properties: |
    {{- range $key, $value := .Values.config }}
      {{- $valueStr := printf "%v" $value }}
      {{- if and (regexMatch "^[0-9]+$" $valueStr) (lt (len $valueStr) 10) }}
        {{ $key }}={{ $valueStr }}
      {{- else if regexMatch "^[0-9]+\\.[0-9]+$" $valueStr }}
        {{ $key }}={{ printf "%.1f" $value }}
      {{- else if eq (typeOf $value) "float64" }}
        {{ $key }}={{ $value | int64 }}
      {{- else if eq (typeOf $value) "[]interface {}" }}
        {{ $key }}={{ $value | join "," }}
      {{- else }}
        {{ $key }}={{ $value }}
      {{- end }}
    {{- end }}
        capacity.config.file=config/{{ .Values.capacity.type }}.json

  clusterConfigs.json: |
    {{- .Values.cluster | toPrettyJson | nindent 4 }}

  {{ .Values.capacity.type }}.json: |
    {{- .Values.capacity.config | nindent 4 }}

  {{- if .Values.jaas.enabled }}
  cruise_control_jaas.conf: |
    {{- .Values.jaas.config | nindent 4 }}
  {{- end }}

  log4j.properties: |
    {{- range $key, $value := .Values.log4j }}
      {{ $key }}={{ $value }}
    {{- end }}
