sources:
  cruise-control:
    kind: dockerimage
    spec:
      image: devopsiaci/cruise-control
      architecture: linux/amd64
      tagfilter: "jdk17-cc*"
conditions: {}
targets:
  cruise-control-helm:
    name: bump cruise-control helm chart
    kind: helmchart
    spec:
      name: charts/cruise-control
      file: Chart.yaml
      key: $.appVersion
      versionincrement: patch
    sourceid: cruise-control
